INSERT INTO Song (id, title, artist, genre, duration) VALUES (2, 'Hotel California', 'Eagles', 'Rock', 390);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (3, 'Grauer Rauch', 'Jonny 5', 'Rap', 123);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (4, 'Imagine', 'John Lennon', 'Pop', 183);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (5, 'Hey Jude', 'The Beatles', 'Pop', 431);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (6, 'Stairway to Heaven', 'Led Zeppelin', 'Rock', 482);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (7, 'Like a Rolling Stone', 'Bob Dylan', 'Rock', 369);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (8, 'Smells Like Teen Spirit', 'Nirvana', 'Grunge', 301);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (9, 'Imagine Dragons', 'Radioactive', 'Alternative', 187);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (10, 'Thriller', 'Michael Jackson', 'Pop', 357);
INSERT INTO Song (id, title, artist, genre, duration) VALUES (11, 'Sweet Child O'' Mine', 'Guns N'' Roses', 'Rock', 356);